CREATE TABLE work_units (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR NOT NULL,
	date DATE NOT NULL,
	week INTEGER NOT NULL,
	start TIME NOT NULL,
	end TIME NOT NULL,
	remark VARCHAR,
	processed BOOLEAN NOT NULL DEFAULT 'f'
)
